version: '3.8'
services:
  db:
    image: mariadb:latest
    environment:
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: database
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 8080:3306
