version: '3.8'
services:
  db:
    image: mariadb:latest
    environment:
      MARIADB_USER: DB_USERNAME
      MARIADB_PASSWORD: DB_PASSWORD
      MARIADB_DATABASE: database
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - app-network

  api:
    build: ./api
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      TOKEN_SECRET: ${TOKEN_SECRET}
    ports:
      - 8081:8081
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ./app
    depends_on:
      - api
    ports:
      - 3000:80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
