version: '3.8'
services:
  db:
    container_name: ${DB_CONTAINER_NAME}
    build: ./database
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - app-network
    environment:
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}

      - DEBUG=${DEBUG}

  api:
    container_name: ${API_CONTAINER_NAME}
    build: ./API
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_CONTAINER_NAME=${DB_CONTAINER_NAME}
      - DB_PORT=${DB_PORT}

      - TOKEN_SECRET=${TOKEN_SECRET}

      - DEBUG=${DEBUG}
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh

  frontend:
    container_name: ${APP_CONTAINER_NAME}
    build: ./app
    depends_on:
      - api
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - app-network
    environment:
      - DEBUG=${DEBUG}

networks:
  app-network:
    driver: bridge
