name: Build and Push Docker Images and Run Integration Tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
        - dev


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push images
      run: |
        docker-compose build
        docker-compose up -d

  run-integration-tests:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Playwright
      uses: microsoft/playwright-github-action@v1

    - name: Run integration tests
      run: |
        cd ./integration-tests
        npx playwright test
      env: 
        PLAYWRIGHT_BROWSERS: chromium
