name: Integration Tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Run project containers
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}

          DB_CONTAINER_NAME: ${{ vars.DB_CONTAINER_NAME }}
          DB_PORT: ${{ vars.DB_PORT }}

          API_CONTAINER_NAME: ${{ vars.API_CONTAINER_NAME }}
          API_PORT: ${{ vars.API_PORT }}

          APP_CONTAINER_NAME: ${{ vars.APP_CONTAINER_NAME }}
          APP_PORT: ${{ vars.APP_PORT }}

          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}

          PROD_ENV: ${{ vars.PROD_ENV }}
          ADD_DATA: ${{ vars.ADD_DATA }}
        run: docker-compose up -d --build

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./integration-tests
        run: npm ci

      - name: Initialize Playwright
        working-directory: ./integration-tests
        run: npx playwright install

      - name: Run tests
        working-directory: ./integration-tests
        run: npx playwright test
        env:
          PLAYWRIGHT_BROWSERS: chromium
