name: Unit Tests on Backend & Frontend

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  test-backend:
    runs-on: ubuntu-latest
    env:
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_CONTAINER_NAME: ${{ env.DB_CONTAINER_NAME }}
      DB_PORT: ${{ env.DB_PORT }}

      TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./API
        run: npm ci

      - name: Run tests
        working-directory: ./API
        run: npm run test

  test-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./app
        run: npm ci

      - name: Run tests
        working-directory: ./app
        run: npm run test
