name: Unit Tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./API
        run: npm ci

      - name: Run tests
        working-directory: ./API
        env:
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
        run: npm run test

  test-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./app
        run: npm ci

      - name: Run tests
        working-directory: ./app
        run: npm run test
